version: 0.0
os: linux
files:
  - source: ./Orchestrator-1.0-SNAPSHOT.jar
    destination: /home/ubuntu/have-blue

hooks:
  ApplicationStop:
    - location: stop-have-blue.sh
      timeout: 180
      runas: root
  ApplicationStart:
    - location: start-have-blue.sh
      timeout: 180
      runas: root
